
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_link_development

production:
  <<: *default
  host: app-link-prod.cvspj2f5xy55.ap-south-1.rds.amazonaws.com
  port: 5432  
  database: app_link_prod
  username: app_link_prod
  password: app_link_prod
