
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  host: jiffle-login-production.cv2qr9eokzp0.us-east-2.rds.amazonaws.com
  port: 5432  
  database: jiffle_login_production
  username: jiffle_login_production
  password: jiffle_login_production
